env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
plugins:
  - react
rules: { 'react/react-in-jsx-scope': 'off', 'object-curly-newline': 'off', 'comma-dangle': 'off',
'jsx-a11y/no-autofocus': [ 0, {
            'ignoreNonDOM': true
        }],
'operator-linebreak': ['error', 'after', { 'overrides': { '?': 'before', ':': 'before' } }],
'react/function-component-definition': [
  2,
  {
    namedComponents: ['arrow-function', 'function-declaration'],
    unnamedComponents: 'arrow-function',
  },
],
'no-shadow': 'off',
 'implicit-arrow-linebreak': 0,
 'indent': 'off',
 'no-param-reassign': 0
}
